### ISSUE TITLE
Feature / Inforrmation

### ISSUE THREAD

**Issue by Kaelber** [galilley/syncthing-pyselective#3]
Is possible to have a complet v0.2.2 with the EXE or in which way the source files can implement?

I gave in the thread https://forum.syncthing.net/t/selective-sync-feature-most-important/16394/37 a note to your tool, are you involved in such discussions?

It would be good to have a possibility to store different installations. I use 3-4 Synology NAS on which 2 instances of Syncthing are installed each, then different desktop computers and Android Smartphones. Would be possible such a feature?

**Comment by galilley** [comment]
Dear Kaelber,
Sorry for the delay, I still can not find the option to receive notifications about the issues...

Selective Sync is really demanded feature that is why I've started this project. The discussion is quite old. I've put my first message with the link [here](https://forum.syncthing.net/t/selective-sync/84/44). I didn't see the thread you mentioned, but I will read it carefully and I really surprised that people have mentioned this project :).

I'm waiting with the EXE for 0.2.2 as I'm going to implement a few features in the next week and I will build the EXE right after.

Also I do not recognize completely your feature request. Would you like to switch between two (or more) Syncthing instance? So we will need to store two api keys and urls?

**Comment by galilley** [comment]
Must be fixed in version [0.3.0](https://github.com/galilley/syncthing-pyselective/releases/tag/v0.3.0), please check and reopen if problem appears again.
