### ISSUE TITLE
Remote Use

### ISSUE THREAD

**Issue by MikeBishop** [galilley/syncthing-pyselective#4]
I'd like to be able to do something like this despite not being at either computer running the SyncThing processes. Would it be reasonable to have a mode where both sides are accessed by IP address? Or perhaps expose a web interface like SyncThing does, rather than a local graphical interface?

In my target use case, one endpoint is a headless NAS and the other is a media machine with a 10-foot UI and SSH access.

**Comment by galilley** [comment]
Dear Mike,
I'm really do not understand the issue... Why you can not just put the IP address of your NAS into the URL field instead of the localhost? A problem could appear if your SyncThing web interface is protected by the password. As far as I remember the API key will not work in this case.

**Comment by galilley** [comment]
Yes, it is true, please see the attached image. So, I will close the issue. Please let me know if your use case is different.

![Screenshot_20240303_232115](https://github.com/galilley/syncthing-pyselective/assets/24869902/2702c587-0841-4097-b884-b432e63038d3)
